### ISSUE TITLE
test.py gives ValueError upon EXECUTION

### ISSUE THREAD

**Issue by abiha-inam123** [dhyeythumar/PPO-algo-with-custom-Unity-environment#4] opened 2022-02-02 16:58 UTC
Dear sir,
I am facing the following error as I am trying to run the test.py file. upon execution unity launches for a second and then it closes and gives the following ValueError can you please guide me on how to resolve this problem?
following is the whole data I get after executing the test.py.

--------------------------------------------------------------------------------------------------------------------------------------------
(myvenv_unity) C:\Users\Blessing Computer\PPO-algo>python test.py
2022-02-02 01:27:58.717925: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2022-02-02 01:27:58.718621: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

                Using ./training_data/model/train-1/actor_51.hdf5 saved model for testing.

2022-02-02 01:28:13.496256: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2022-02-02 01:28:13.621982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:03:00.0 name: GeForce GT 720M computeCapability: 2.1
coreClock: 1.55GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 13.41GiB/s
2022-02-02 01:28:13.623311: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2022-02-02 01:28:13.625928: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2022-02-02 01:28:13.626900: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2022-02-02 01:28:13.627858: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2022-02-02 01:28:13.628814: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2022-02-02 01:28:13.629776: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2022-02-02 01:28:13.630731: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2022-02-02 01:28:13.631077: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-02-02 01:28:13.633041: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-02 01:28:13.680139: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x21272230490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-02-02 01:28:13.680648: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-02-02 01:28:13.683532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:

    2022-02-02 01:28:13.683921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
    WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
    WARNING:tensorflow:Model was constructed with shape (None, 54) for input Tensor("observation_input:0", shape=(None, 54), dtype=float32), but it was called on an input with incompatible shape (1, 52).
    Traceback (most recent call last):
      File "test.py", line 126, in <module>
        agent.test()
      File "test.py", line 94, in test
        action_probs = self.actor.predict(state, steps=1)  # (1, 2)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\training.py", line 130, in _method_wrapper
        return method(self, *args, **kwargs)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1599, in predict
        tmp_batch_outputs = predict_function(iterator)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
        result = self._call(*args, **kwds)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
        self._initialize(args, kwds, add_initializers_to=initializers)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\eager\def_function.py", line 696, in _initialize
        self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
        graph_function, _, _ = self._maybe_define_function(args, kwargs)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\eager\function.py", line 3065, in _create_graph_function
        func_graph_module.func_graph_from_py_func(
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
        return weak_wrapped_fn().__wrapped__(*args, **kwds)
      File "C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
        raise e.ag_error_metadata.to_exception(e)
    ValueError: in user code:
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  
            return step_function(self, iterator)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function 
            outputs = model.distribute_strategy.run(run_step, args=(data,))
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
            return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
            return self._call_for_each_replica(fn, args, kwargs)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
            return fn(*args, **kwargs)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
            outputs = model.predict_step(data)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
            return self(x, training=False)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
            outputs = call_fn(inputs, *args, **kwargs)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\functional.py:385 call
            return self._run_internal_graph(
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\functional.py:508 _run_internal_graph
            outputs = node.layer(*args, **kwargs)
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
            input_spec.assert_input_compatibility(self.input_spec, inputs,
        C:\Users\Blessing Computer\myvenv_unity\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:212 assert_input_compatibility
            raise ValueError(

    ValueError: Input 0 of layer fc1 is incompatible with the layer: expected axis -1 of input shape to have value 54 but received input with shape [1, 52]

**Comment by BazilaAfridi** [comment] 2022-02-02 17:13
@dhyeythumar Yes sir I'm also getting the same issue don't know what is the reason behind this value error.

**Comment by dhyeythumar** [comment] 2022-02-03 04:50
Hi @abiha-inam123 & @BazilaAfridi,
There was minor bug in test.py file, I have fixed it you can check it [here](https://github.com/dhyeythumar/PPO-algo-with-custom-Unity-environment/commit/887ebeae522cb7b374a42c8d2825de04272e7c7e#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2e)

**Comment by BazilaAfridi** [comment] 2022-02-03 10:37
OK, sir thank you so much for your quick response.

**Comment by dhyeythumar** [comment] 2022-02-04 14:29
Closing this issue as the problem is resolved.

**Closed by dhyeythumar** 2022-02-04 14:29 UTC
